CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)		NOT NULL,
	PRIMARY KEY(ID))
GO

CREATE TABLE CATEGORIA(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID))
GO

CREATE TABLE CONTA(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	VALOR			DECIMAL(18,2)		NOT NULL,
	DATA			DATE				NOT NULL,
	OBSERVACOES		NVARCHAR(500)		NOT NULL,
	TIPO			INTEGER				NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	IDCATEGORIA		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(ID))
GO